### ISSUE TITLE
Custom palettes?

### ISSUE THREAD

**Issue by CookieJon** [igor-bezkrovny/image-quantization#7]
Hi, this library is fantastic, but it would be even better if there were a clear or simple way to use a custom palette _with the colors already defined_ to which to resample the image.

Or perhaps this is already possible?  Can you advise... at the moment I'm trying to hack the "Point" and "Palette" objects and stuff them with my own values but perhaps there's an easier way?

Thanks.
CJ.

**Comment by igor-bezkrovny** [comment]
Hi,

I created small demo for you:
https://github.com/igor-bezkrovny/image-quantization/tree/master/demo/apply-palette-from-file

Here I load palette.png (8bit (indexed) file with only 32 colors in its palette), and apply this palette to 3 different files. 

New png files are saved to folder `out` in 32bit PNG because pngjs doesn't know how to write 256color png. However these files uses only colors from palette + 1 (see below first pngjs issue for answer why +1).

### pngjs issues:
- no support palette with color number not equal to 256, palette always contains 256 quadruplets
- crashes on opening 8bit (indexed) file with RGBA palette and with size 1x1. Need at least 4 pixels in image
- no support for saving 8bit (indexed) file

**Comment by CookieJon** [comment]
> Does it answers to your question?

Yes, perfectly thanks very much!   :+1: 

My palettes are all JS objects, not files, but it makes little difference to the method you've shown me (and I've also picked up a lot of tips just from your code style too :-)

Thanks for going to the effort.  Pulling all those libraries and algorithms together into  this project is a huge achievement, and I'm very grateful I can benefit from all you hard work, though it seems wrong somehow lol.
